# fly.toml app configuration file generated for job-ads on 2023-06-14T02:57:06+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "job-ads"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
